namespace backend.Services
{
    public class WordCategorizationService
    {
        // Méthode simple basée sur des listes de mots pour la démo
        private static readonly Dictionary<string, string> GrammaticalHints = new()
        {
            // Articles
            { "l'", "article défini" }, { "au", "article contracté" }, { "aux", "article contracté" },
            // Pronoms
            { "on", "pronom indéfini" }, { "cela", "pronom démonstratif" }, { "ceci", "pronom démonstratif" },
            // Noms communs supplémentaires
            { "pain", "nom commun" }, { "eau", "nom commun" }, { "feu", "nom commun" }, { "air", "nom commun" }, { "terre", "nom commun" }, { "lumière", "nom commun" }, { "ombre", "nom commun" }, { "route", "nom commun" }, { "chemin", "nom commun" }, { "forêt", "nom commun" }, { "montagne", "nom commun" }, { "rivière", "nom commun" }, { "lac", "nom commun" }, { "mer", "nom commun" }, { "océan", "nom commun" }, { "plage", "nom commun" }, { "colline", "nom commun" }, { "village", "nom commun" }, { "campagne", "nom commun" }, { "ville", "nom commun" }, { "quartier", "nom commun" }, { "région", "nom commun" }, { "continent", "nom commun" }, { "univers", "nom commun" }, { "galaxie", "nom commun" }, { "étoile", "nom commun" }, { "planète", "nom commun" }, { "lune", "nom commun" }, { "soleil", "nom commun" }, { "nuage", "nom commun" }, { "pluie", "nom commun" }, { "neige", "nom commun" }, { "vent", "nom commun" }, { "orage", "nom commun" }, { "tempête", "nom commun" }, { "arc", "nom commun" }, { "flèche", "nom commun" }, { "épée", "nom commun" }, { "bouclier", "nom commun" }, { "casque", "nom commun" }, { "armure", "nom commun" }, { "cheval", "nom commun" }, { "chien", "nom commun" }, { "oiseau", "nom commun" }, { "poisson", "nom commun" }, { "insecte", "nom commun" }, { "papillon", "nom commun" }, { "abeille", "nom commun" }, { "fourmi", "nom commun" }, { "araignée", "nom commun" }, { "serpent", "nom commun" }, { "grenouille", "nom commun" }, { "souris", "nom commun" }, { "rat", "nom commun" }, { "vache", "nom commun" }, { "mouton", "nom commun" }, { "cochon", "nom commun" }, { "poule", "nom commun" }, { "canard", "nom commun" }, { "dinde", "nom commun" }, { "lapin", "nom commun" }, { "chèvre", "nom commun" }, { "lion", "nom commun" }, { "tigre", "nom commun" }, { "ours", "nom commun" }, { "loup", "nom commun" }, { "singe", "nom commun" }, { "éléphant", "nom commun" }, { "girafe", "nom commun" }, { "zèbre", "nom commun" }, { "hippopotame", "nom commun" }, { "rhinocéros", "nom commun" }, { "crocodile", "nom commun" }, { "tortue", "nom commun" }, { "dauphin", "nom commun" }, { "requin", "nom commun" }, { "baleine", "nom commun" }, { "pieuvre", "nom commun" }, { "crabe", "nom commun" }, { "homard", "nom commun" }, { "crevette", "nom commun" }, { "huître", "nom commun" }, { "escargot", "nom commun" }, { "moule", "nom commun" }, { "coquillage", "nom commun" },
            // Verbes supplémentaires
            { "marcher", "verbe" }, { "nager", "verbe" }, { "voler", "verbe" }, { "sauter", "verbe" }, { "ramper", "verbe" }, { "grimper", "verbe" }, { "creuser", "verbe" }, { "planter", "verbe" }, { "cueillir", "verbe" }, { "moudre", "verbe" }, { "cuire", "verbe" }, { "bouillir", "verbe" }, { "frire", "verbe" }, { "rôtir", "verbe" }, { "griller", "verbe" }, { "mélanger", "verbe" }, { "verser", "verbe" }, { "servir", "verbe" }, { "dormir", "verbe" }, { "réveiller", "verbe" }, { "rêver", "verbe" }, { "penser", "verbe" }, { "croire", "verbe" }, { "espérer", "verbe" }, { "aider", "verbe" }, { "soigner", "verbe" }, { "guérir", "verbe" }, { "blesser", "verbe" }, { "tuer", "verbe" }, { "vivre", "verbe" }, { "mourir", "verbe" }, { "naître", "verbe" }, { "grandir", "verbe" }, { "vieillir", "verbe" }, { "jouer", "verbe" }, { "rire", "verbe" }, { "pleurer", "verbe" }, { "chanter", "verbe" }, { "danser", "verbe" }, { "peindre", "verbe" }, { "dessiner", "verbe" }, { "sculpter", "verbe" }, { "lire", "verbe" }, { "écrire", "verbe" }, { "compter", "verbe" }, { "calculer", "verbe" }, { "mesurer", "verbe" }, { "peser", "verbe" }, { "couper", "verbe" }, { "coudre", "verbe" }, { "tricoter", "verbe" }, { "broder", "verbe" }, { "laver", "verbe" }, { "nettoyer", "verbe" }, { "balayer", "verbe" }, { "essuyer", "verbe" }, { "ranger", "verbe" }, { "organiser", "verbe" }, { "préparer", "verbe" }, { "finir", "verbe" }, { "commencer", "verbe" }, { "continuer", "verbe" }, { "arrêter", "verbe" }, { "changer", "verbe" }, { "transformer", "verbe" }, { "améliorer", "verbe" }, { "empirer", "verbe" }, { "diminuer", "verbe" }, { "augmenter", "verbe" }, { "ajouter", "verbe" }, { "enlever", "verbe" }, { "remplacer", "verbe" }, { "choisir", "verbe" }, { "refuser", "verbe" }, { "accepter", "verbe" }, { "demander", "verbe" }, { "répondre", "verbe" }, { "questionner", "verbe" }, { "expliquer", "verbe" }, { "enseigner", "verbe" }, { "apprendre", "verbe" }, { "comprendre", "verbe" }, { "ignorer", "verbe" }, { "oublier", "verbe" }, { "se souvenir", "verbe" },
            // Adjectifs supplémentaires
            { "rouge", "adjectif" }, { "bleu", "adjectif" }, { "vert", "adjectif" }, { "jaune", "adjectif" }, { "noir", "adjectif" }, { "blanc", "adjectif" }, { "gris", "adjectif" }, { "orange", "adjectif" }, { "rose", "adjectif" }, { "violet", "adjectif" }, { "marron", "adjectif" }, { "doré", "adjectif" }, { "argenté", "adjectif" }, { "coloré", "adjectif" }, { "fade", "adjectif" }, { "amer", "adjectif" }, { "sucré", "adjectif" }, { "salé", "adjectif" }, { "acide", "adjectif" }, { "épicé", "adjectif" }, { "piquant", "adjectif" }, { "doux", "adjectif" }, { "moelleux", "adjectif" }, { "dur", "adjectif" }, { "mou", "adjectif" }, { "sec", "adjectif" }, { "humide", "adjectif" }, { "glacé", "adjectif" }, { "brûlant", "adjectif" }, { "frais", "adjectif" }, { "ancien", "adjectif" }, { "moderne", "adjectif" }, { "jeune", "adjectif" }, { "vieux", "adjectif" }, { "riche", "adjectif" }, { "pauvre", "adjectif" }, { "simple", "adjectif" }, { "complexe", "adjectif" }, { "clair", "adjectif" }, { "sombre", "adjectif" }, { "lumineux", "adjectif" }, { "obscur", "adjectif" }, { "proche", "adjectif" }, { "lointain", "adjectif" }, { "haut", "adjectif" }, { "bas", "adjectif" }, { "large", "adjectif" }, { "étroit", "adjectif" }, { "épais", "adjectif" }, { "mince", "adjectif" }, { "profond", "adjectif" }, { "superficiel", "adjectif" },
            // Adverbes supplémentaires
            { "ici", "adverbe" }, { "là-bas", "adverbe" }, { "partout", "adverbe" }, { "ailleurs", "adverbe" }, { "dedans", "adverbe" }, { "dehors", "adverbe" }, { "en haut", "adverbe" }, { "en bas", "adverbe" }, { "devant", "adverbe" }, { "derrière", "adverbe" }, { "près", "adverbe" }, { "loin", "adverbe" }, { "vite", "adverbe" }, { "lentement", "adverbe" }, { "bruyamment", "adverbe" }, { "silencieusement", "adverbe" }, { "doucement", "adverbe" }, { "fortement", "adverbe" }, { "clairement", "adverbe" }, { "obscurément", "adverbe" }, { "simplement", "adverbe" }, { "complexement", "adverbe" }, { "joyeusement", "adverbe" }, { "tristement", "adverbe" }, { "heureusement", "adverbe" }, { "malheureusement", "adverbe" }, { "rapidement", "adverbe" }, { "lentement", "adverbe" }, { "précisément", "adverbe" }, { "exactement", "adverbe" }, { "environ", "adverbe" }, { "presque", "adverbe" }, { "totalement", "adverbe" }, { "partiellement", "adverbe" }, { "surtout", "adverbe" }, { "rarement", "adverbe" }, { "parfois", "adverbe" }, { "toujours", "adverbe" }, { "jamais", "adverbe" },
        // ...existing mots et catégories...
            // Articles définis/indéfinis
            { "le", "article défini" }, { "la", "article défini" }, { "les", "article défini" },
            { "un", "article indéfini" }, { "une", "article indéfini" }, { "des", "article indéfini" },
            { "du", "article partitif" }, { "de la", "article partitif" }, { "de l'", "article partitif" }, { "des", "article partitif" },
            // Pronoms personnels
            { "je", "pronom personnel" }, { "tu", "pronom personnel" }, { "il", "pronom personnel" }, { "elle", "pronom personnel" }, { "nous", "pronom personnel" }, { "vous", "pronom personnel" }, { "ils", "pronom personnel" }, { "elles", "pronom personnel" },
            // Pronoms possessifs
            { "mon", "pronom possessif" }, { "ma", "pronom possessif" }, { "mes", "pronom possessif" }, { "ton", "pronom possessif" }, { "ta", "pronom possessif" }, { "tes", "pronom possessif" }, { "son", "pronom possessif" }, { "sa", "pronom possessif" }, { "ses", "pronom possessif" },
            { "notre", "pronom possessif" }, { "nos", "pronom possessif" }, { "votre", "pronom possessif" }, { "vos", "pronom possessif" }, { "leur", "pronom possessif" }, { "leurs", "pronom possessif" },
            // Pronoms démonstratifs
            { "ce", "pronom démonstratif" }, { "cet", "pronom démonstratif" }, { "cette", "pronom démonstratif" }, { "ces", "pronom démonstratif" },
            // Pronoms relatifs
            { "qui", "pronom relatif" }, { "que", "pronom relatif" }, { "quoi", "pronom relatif" }, { "dont", "pronom relatif" }, { "où", "pronom relatif" },
            // Pronoms interrogatifs
            { "lequel", "pronom interrogatif" }, { "laquelle", "pronom interrogatif" }, { "lesquels", "pronom interrogatif" }, { "lesquelles", "pronom interrogatif" },
            // Noms communs (exemples variés)
            { "maison", "nom commun" }, { "chat", "nom commun" }, { "voiture", "nom commun" }, { "arbre", "nom commun" }, { "livre", "nom commun" }, { "table", "nom commun" }, { "ordinateur", "nom commun" }, { "fenêtre", "nom commun" }, { "porte", "nom commun" }, { "stylo", "nom commun" }, { "chaise", "nom commun" }, { "fleur", "nom commun" }, { "ville", "nom commun" }, { "pays", "nom commun" }, { "rue", "nom commun" }, { "école", "nom commun" }, { "professeur", "nom commun" }, { "élève", "nom commun" }, { "travail", "nom commun" }, { "argent", "nom commun" }, { "temps", "nom commun" }, { "année", "nom commun" }, { "jour", "nom commun" }, { "semaine", "nom commun" }, { "mois", "nom commun" }, { "heure", "nom commun" }, { "minute", "nom commun" }, { "seconde", "nom commun" },
            // Noms propres
            { "Paris", "nom propre" }, { "France", "nom propre" }, { "Jean", "nom propre" }, { "Marie", "nom propre" }, { "Lyon", "nom propre" }, { "Europe", "nom propre" },
            // Verbes courants et variés
            { "manger", "verbe" }, { "être", "verbe" }, { "avoir", "verbe" }, { "aller", "verbe" }, { "faire", "verbe" }, { "dire", "verbe" }, { "voir", "verbe" }, { "savoir", "verbe" }, { "pouvoir", "verbe" }, { "vouloir", "verbe" }, { "venir", "verbe" }, { "prendre", "verbe" }, { "mettre", "verbe" }, { "donner", "verbe" }, { "parler", "verbe" }, { "aimer", "verbe" }, { "finir", "verbe" }, { "choisir", "verbe" }, { "partir", "verbe" }, { "sortir", "verbe" }, { "ouvrir", "verbe" }, { "lire", "verbe" }, { "écrire", "verbe" }, { "courir", "verbe" }, { "jouer", "verbe" }, { "travailler", "verbe" }, { "étudier", "verbe" }, { "acheter", "verbe" }, { "vendre", "verbe" }, { "attendre", "verbe" }, { "recevoir", "verbe" }, { "apprendre", "verbe" }, { "comprendre", "verbe" }, { "descendre", "verbe" }, { "monter", "verbe" }, { "rentrer", "verbe" }, { "tomber", "verbe" }, { "arriver", "verbe" }, { "passer", "verbe" }, { "rester", "verbe" }, { "entrer", "verbe" }, { "sortir", "verbe" }, { "retourner", "verbe" }, { "mourir", "verbe" }, { "naître", "verbe" },
            // Adjectifs variés
            { "beau", "adjectif" }, { "grand", "adjectif" }, { "petit", "adjectif" }, { "jeune", "adjectif" }, { "vieux", "adjectif" }, { "nouveau", "adjectif" }, { "bon", "adjectif" }, { "mauvais", "adjectif" }, { "gentil", "adjectif" }, { "heureux", "adjectif" }, { "triste", "adjectif" }, { "facile", "adjectif" }, { "difficile", "adjectif" }, { "rapide", "adjectif" }, { "lent", "adjectif" }, { "fort", "adjectif" }, { "faible", "adjectif" }, { "propre", "adjectif" }, { "sale", "adjectif" }, { "chaud", "adjectif" }, { "froid", "adjectif" }, { "clair", "adjectif" }, { "sombre", "adjectif" }, { "long", "adjectif" }, { "court", "adjectif" },
            // Adverbes variés
            { "vite", "adverbe" }, { "bien", "adverbe" }, { "mal", "adverbe" }, { "souvent", "adverbe" }, { "toujours", "adverbe" }, { "jamais", "adverbe" }, { "déjà", "adverbe" }, { "tard", "adverbe" }, { "ici", "adverbe" }, { "là", "adverbe" }, { "demain", "adverbe" }, { "hier", "adverbe" }, { "après", "adverbe" }, { "avant", "adverbe" }, { "ensemble", "adverbe" }, { "seul", "adverbe" }, { "très", "adverbe" }, { "peu", "adverbe" }, { "beaucoup", "adverbe" }, { "assez", "adverbe" }, { "plutôt", "adverbe" }, { "presque", "adverbe" }, { "parfois", "adverbe" }, { "rarement", "adverbe" },
            // Prépositions variées
            { "à", "préposition" }, { "de", "préposition" }, { "pour", "préposition" }, { "avec", "préposition" }, { "sans", "préposition" }, { "chez", "préposition" }, { "dans", "préposition" }, { "sur", "préposition" }, { "sous", "préposition" }, { "devant", "préposition" }, { "derrière", "préposition" }, { "entre", "préposition" }, { "par", "préposition" }, { "contre", "préposition" }, { "vers", "préposition" }, { "depuis", "préposition" }, { "pendant", "préposition" }, { "malgré", "préposition" }, { "selon", "préposition" }, { "grâce à", "préposition" },
            // Conjonctions variées
            { "et", "conjonction de coordination" }, { "mais", "conjonction de coordination" }, { "ou", "conjonction de coordination" }, { "donc", "conjonction de coordination" }, { "or", "conjonction de coordination" }, { "ni", "conjonction de coordination" }, { "car", "conjonction de coordination" }, { "que", "conjonction de subordination" }, { "quand", "conjonction de subordination" }, { "comme", "conjonction de subordination" }, { "si", "conjonction de subordination" }, { "lorsque", "conjonction de subordination" }, { "puisque", "conjonction de subordination" }, { "parce que", "conjonction de subordination" }, { "afin que", "conjonction de subordination" }, { "avant que", "conjonction de subordination" }, { "après que", "conjonction de subordination" }, { "bien que", "conjonction de subordination" }, { "quoique", "conjonction de subordination" },
            // Interjections variées
            { "oh", "interjection" }, { "ah", "interjection" }, { "eh", "interjection" }, { "zut", "interjection" }, { "bravo", "interjection" }, { "hélas", "interjection" }, { "ouf", "interjection" }, { "tiens", "interjection" }, { "chut", "interjection" },
        };

        public string Categorize(string word)
        {
            if (string.IsNullOrWhiteSpace(word)) return "inconnu";
            word = word.ToLowerInvariant();
            if (GrammaticalHints.TryGetValue(word, out var category))
                return category;

            // Règles morphologiques avancées
            if (word.EndsWith("er") || word.EndsWith("ir") || word.EndsWith("re") || word.EndsWith("oir") || word.EndsWith("dre") || word.EndsWith("tre")) return "verbe";
            if (word.EndsWith("ment") || word.EndsWith("emment") || word.EndsWith("amment")) return "adverbe";
            if (word.EndsWith("tion") || word.EndsWith("sion") || word.EndsWith("age") || word.EndsWith("ure") || word.EndsWith("té") || word.EndsWith("isme") || word.EndsWith("ence") || word.EndsWith("ance") || word.EndsWith("eur") || word.EndsWith("ette") || word.EndsWith("ade") || word.EndsWith("ure")) return "nom commun";
            if (word.EndsWith("eux") || word.EndsWith("euse") || word.EndsWith("if") || word.EndsWith("ive") || word.EndsWith("al") || word.EndsWith("elle") || word.EndsWith("ien") || word.EndsWith("ienne")) return "adjectif";
            if (word.Length <= 3 && (word == "le" || word == "la" || word == "un" || word == "une" || word == "des")) return "article";
            if (word.Length <= 3 && (word == "et" || word == "ou" || word == "ni" || word == "mais")) return "conjonction";
            if (word.Length <= 4 && (word == "chez" || word == "dans" || word == "avec" || word == "pour")) return "préposition";
            return "inconnu";
        }
    }
}
